server:
    port: 8484

spring:
    application:
        name: kkregistry

registry:
    serverlist:
        - http://192.168.110.220:8484
        - http://192.168.110.220:8485
        - http://192.168.110.220:8486